export const serviceEndPoint = {
  roleServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/role",
  userProfileServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/users",
  enrollmentServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/enroll",
  educationServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/education",
  familyServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/family",
  experienceServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/experience",
  observationServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/observationservice",
  engagementServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/engagement",
  addressServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/address",
  stateServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/stateservice",
  cityVillageServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/cityvillageservice",
  batchDetailsServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/batchdetails",
//  engagementServiceEndPoint:"http://playground.tatastrive.com/sservices-v1/engagement",
  documentServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/documents",
  salutationServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/salutationservice",
  genderServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/genderservice",
  courseServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/courseservice",
  interestinventoryServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/interestInventory",
  saveIIServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/saveInterestInventoryDocument",
  centerServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/centerservice",
  counsellingServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/counselling",
  studentServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/student",
  evaluationServiceEndPoint:"http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/evaluation",
  qualificationServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/qualificationservice",
  categoryServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/categoryservice",
  mobchannelServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/mobchannelservice",
  religionServiceEndPoint:"http://uat-platform.tatastrive.com/services-v1/religionservice",
  businessCaseEndPoint: "http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/businesscase",
  knackServiceEndPoint : "http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/knack",
  uploadServiceEndPoint : "http://uat-platform.tatastrive.com/ssservices-v1/sservices-v1/uploadFile",
  loginService : "http://uat-platform.tatastrive.com/ssservices-v1/login",
  businessCaseBriefMdmService : "http://uat-platform.tatastrive.com/services-v1/bibservice"
         
};