export const serviceEndPoint = {
  roleServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/role",
  userProfileServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/users",
  enrollmentServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/enroll",
  educationServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/education",
  //familyServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/family",
  familyServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/family",
  socioeconomicServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/socioEconomic",
 // socioeconomicServiceEndPoint:"http://localhost:8081/socioEconomic",
  experienceServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/experience",
  observationServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/observationservice",
  engagementServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/engagement",
  addressServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/address",
  stateServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/stateservice",
  cityVillageServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/cityvillageservice",
  batchDetailsServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/batchdetails",
//  engagementServiceEndPoint:"http://playground.tatastrive.com/sservices-v1/engagement",
  documentServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/documents",
  salutationServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/salutationservice",
  genderServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/genderservice",
  courseServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/courseservice",
  interestinventoryServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/interestInventory",
  saveIIServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/saveInterestInventoryDocument",
  centerServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/centerservice",
  cityVillageServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/cityvillageservice",
  counsellingServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/counselling",
  studentServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/student",
  evaluationServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/evaluation",
  qualificationServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/qualificationservice",
  categoryServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/categoryservice",
  mobchannelServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/mobchannelservice",
  religionServiceEndPoint:process.env.REACT_APP_API_ENDPOINT+"services-v1/religionservice",
  businessCaseEndPoint: process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/businesscase",
  knackServiceEndPoint : process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/knack",
  uploadServiceEndPoint : process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/uploadFile",
  loginService : process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/login",
  businessCaseBriefMdmService : process.env.REACT_APP_API_ENDPOINT+"services-v1/bibservice",
  dashboardService : process.env.REACT_APP_API_ENDPOINT+"sdservices-v1/dashboard",
  downloadDocument : process.env.REACT_APP_API_ENDPOINT+"Downloads/",
  centerCapacity : process.env.REACT_APP_API_ENDPOINT+"services-v1/centercapacityservice",
  businessIdeaEvaluation  : process.env.REACT_APP_API_ENDPOINT+"services-v1/bieservice",
  masterObservation  : process.env.REACT_APP_API_ENDPOINT+"services-v1/observationservice",
  centerService  : process.env.REACT_APP_API_ENDPOINT+"ssservices-v1/sservices-v1/center",
  mdmExistingBusiness:process.env.REACT_APP_API_ENDPOINT+"services-v1/existingbusiness"
         
};